### ISSUE TITLE
Build issue on Ubuntu

### ISSUE THREAD

**Issue by hzyjerry** [facebookresearch/Replica-Dataset#16] opened 2019-06-24 05:13 UTC
Hi, I'm building on Ubuntu 16.04. After building the latest Pangolin from source, I ran `build.sh` and encountered the following error:

```
Scanning dependencies of target ptex
make[2]: *** No rule to make target '../3rdparty/Pangolin/build/src/libpangolin.so', needed by 'ReplicaSDK/libptex.so'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 30%] Building CXX object ReplicaSDK/CMakeFiles/ptex.dir/ptex/PLYParser.cpp.o
[ 30%] Building CXX object ReplicaSDK/CMakeFiles/ptex.dir/ptex/EGL.cpp.o
[ 30%] Building CXX object ReplicaSDK/CMakeFiles/ptex.dir/ptex/PTexLib.cpp.o
In file included from /home/jerryhe/Desktop/Project/Semantic3D/Replica-Dataset/3rdparty/Pangolin/include/pangolin/display/opengl_render_state.h:30:0,
                 from /home/jerryhe/Desktop/Project/Semantic3D/Replica-Dataset/ReplicaSDK/./include/PTexLib.h:3,
                 from /home/jerryhe/Desktop/Project/Semantic3D/Replica-Dataset/ReplicaSDK/ptex/PTexLib.cpp:2:
/home/jerryhe/Desktop/Project/Semantic3D/Replica-Dataset/3rdparty/Pangolin/include/pangolin/platform.h:30:29: fatal error: pangolin/config.h: No such file or directory
In file included from /home/jerryhe/Desktop/Project/Semantic3D/Replica-Dataset/3rdparty/Pangolin/include/pangolin/image/image.h:30:0,
                 from /home/jerryhe/Desktop/Project/Semantic3D/Replica-Dataset/3rdparty/Pangolin/include/pangolin/image/managed_image.h:30,
                 from /home/jerryhe/Desktop/Project/Semantic3D/Replica-Dataset/ReplicaSDK/./include/MeshData.h:4,
                 from /home/jerryhe/Desktop/Project/Semantic3D/Replica-Dataset/ReplicaSDK/./include/PLYParser.h:4,
                 from /home/jerryhe/Desktop/Project/Semantic3D/Replica-Dataset/ReplicaSDK/ptex/PLYParser.cpp:2:
/home/jerryhe/Desktop/Project/Semantic3D/Replica-Dataset/3rdparty/Pangolin/include/pangolin/platform.h:30:29: fatal error: pangolin/config.h: No such file or directory
compilation terminated.
compilation terminated.
ReplicaSDK/CMakeFiles/ptex.dir/build.make:62: recipe for target 'ReplicaSDK/CMakeFiles/ptex.dir/ptex/PTexLib.cpp.o' failed
make[2]: *** [ReplicaSDK/CMakeFiles/ptex.dir/ptex/PTexLib.cpp.o] Error 1
ReplicaSDK/CMakeFiles/ptex.dir/build.make:86: recipe for target 'ReplicaSDK/CMakeFiles/ptex.dir/ptex/PLYParser.cpp.o' failed
make[2]: *** [ReplicaSDK/CMakeFiles/ptex.dir/ptex/PLYParser.cpp.o] Error 1
CMakeFiles/Makefile2:89: recipe for target 'ReplicaSDK/CMakeFiles/ptex.dir/all' failed
make[1]: *** [ReplicaSDK/CMakeFiles/ptex.dir/all] Error 2
Makefile:83: recipe for target '
```

Thanks for your help!

**Comment by mp3guy** [comment] 2019-06-24 11:02
The build.sh script includes building Pangolin so you shouldn't have to build it yourself from source. It looks like it can't find libpangolin.so which implies it didn't build Pangolin correctly, can you double check the output from the Pangolin build portion of the build.sh script?

**Comment by mpiseno** [comment] 2019-06-25 20:30
I had the same issue. Double check that you have all the Pangolin dependencies here
https://github.com/stevenlovegrove/Pangolin
After I installed Glew this problem was fixed for me. Also do the same for Eigen.

**Comment by jstraub** [comment] 2019-07-10 16:38
Closing this for now - please reopen if problem still persists. I made it more clear in the README to install Pangolin dependencies.

**Closed by jstraub** 2019-07-10 16:38 UTC

**Comment by elientumba2019** [comment] 2020-12-07 11:54
I do havd pangolin and still get this error . any idea what could be the cause ?
